# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Porter < Formula
  desc "Deploy your applications into your own cloud account"
  homepage "https://porter.run"
  version "0.60.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/porter-dev/releases/releases/download/v0.60.2/porter_0.60.2_darwin_amd64"
      sha256 "54725f4cc844747290207b82096452447dce810e1fd01664d56fd801c2cc420c"

      def install
        bin.install "porter_0.60.2_darwin_amd64" => "porter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/porter-dev/releases/releases/download/v0.60.2/porter_0.60.2_darwin_arm64"
      sha256 "d58373761773a661483420962c26493e9256de6196e37b2518f353530b7fb0f2"

      def install
        bin.install "porter_0.60.2_darwin_arm64" => "porter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/porter-dev/releases/releases/download/v0.60.2/porter_0.60.2_linux_amd64"
      sha256 "66add75d185a67a9fef8046ecac4dd75a5079704b0228d3336c67ae450bca3f2"
      def install
        bin.install "porter_0.60.2_linux_amd64" => "porter"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/porter-dev/releases/releases/download/v0.60.2/porter_0.60.2_linux_arm64"
      sha256 "c998b9ff79bf2765307c1bb6cc4789abb599b1f7d0815408ac3693765ec9509d"
      def install
        bin.install "porter_0.60.2_linux_arm64" => "porter"
      end
    end
  end
end
